# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: c37261e1i-capi-aws
  namespace: c37261e1i
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: c37261e1i-capi-aws
subjects:
- kind: ServiceAccount
  name: c37261e1i-capi-aws
